### ISSUE TITLE
AutoFlex issue

### ISSUE THREAD

**Issue by AlexanderWulf** [chasemc/IDBacApp#100]
Hello,

I am a PhD student and I am fascinated by the idea of biotyping some of my bacterial strains using IDBac, however, I am experiencing difficulties running the Autoflex methods on our instrument. Our lab actually does not really use the MALDI, so nobody knows what to do.

I copied the two method files and placed them into the Bruker method folder and then I followed the tutorial to the dot. Everything "works" fine until I try to run the AutoXecute method. It does not matter which one I try, I receive those two messages: 

Referenced Processing   Parameter: 'idBac Small Mol' in AutoXecute method   'IDBac_Small-Molecule_autoX' not found. 
 
Referenced Processing Parameter:   'IDBac_Processing' in AutoXecute method 'IDBac_Protein_autoX' not found.

I can run the individual methods manually, however. Now, I know the problem is probably sitting in front of the computer, but some help would be appreciated. Do I need to change something in the method files?

**Comment by chasemc** [comment]
The autoXectute methods we published were generally for reproducibilty of the paper. You might even want to setup your own autoXecute without those files.

I honestly don't remember which part 'idBac Small Mol'  controls and our instrument is pretty-booked for the next couple of days, but I'll try to find a time to figure this out and report back so that maybe you can use these after all.
 
Also, depending on what "some" means, manual-acquisition might actually provide you higher-quality data.
![image](https://user-images.githubusercontent.com/18691127/55825006-ae8ed280-5aca-11e9-805b-00cb03cf7ac3.png)


Thanks for the detailed message.

**Comment by chasemc** [comment]
The missing file is the processing parameters. 
 
Which can be setup as shown by selecting your method (shown in bottom left) and then the "processing" tab and "new" (shown in bottom middle): 
![111](https://user-images.githubusercontent.com/18691127/55970073-81fec600-5c44-11e9-968c-1787d605b86f.png)

And the file lives in the "ProcessingParameter" directory:
![IMG_0348](https://user-images.githubusercontent.com/18691127/55970507-47e1f400-5c45-11e9-9837-e687b8c94330.jpg)

I've gone ahead added the files here as well:
[IDBAC_methods_2019-04-11.zip](https://github.com/chasemc/IDBacApp/files/3069384/IDBAC_methods_2019-04-11.zip)


I'll be out of the country next week so might be very responsive, but let me know if this solves your problem.

**Comment by AlexanderWulf** [comment]
I just had to update the processing methods. Thank you so much for your help! It works just fine now.
