### ISSUE TITLE
Peak binning with large number of spectra

### ISSUE THREAD

**Issue by davidshumway** [chasemc/IDBacApp#96]
@chasemc I know that you've explained peak binning a few times previously when we've met. However, I am curious if you have any thoughts on why the binning algorithm starts to have issues when facing a large number of spectra?

From the [instruction manual](https://github.com/chasemc/IDBacApp/blob/aacf7625e22e766037adeba3e05ee6d70b54104a/method.md#current-known-limitations-of-idbac):
> MALDIquant's peak binning algorithm begins to falter slightly with a large number of spectra/samples (100's-1000's).

I am curious whether there is a use case in binning large amounts of spectra at once. Do you have any insights on this? In this case, "large" would mean, to start with, what you've identified: 100s to 1000s. Additionally, what about higher ranges: 8,000, 40,000, hundreds of thousands, millions, etc.?

As a side note, I'm browsing maldiquant issue tracker by [this](https://github.com/sgibb/MALDIquant/issues?utf8=%E2%9C%93&q=memory) search. And notice that you are posting an issue within the last hour to the same tracker! :smiley:

**Comment by chasemc** [comment]
Look at the details of MALDIquant's binPeaks: https://rdrr.io/cran/MALDIquant/man/binPeaks-functions.html

To get ideal results you must do binary comparison (each sample to each sample). Even if a group of samples is binned... on search / addition of a new sample it requires O(n) for binning and then a binary calculation (each sample to each sample) for calculating distance (because vector lengths will be different for each binning calculation).

IMO, ideally you would take a vector of masses and a defined ppm value and project this into a higher dimension that accommodates all the samples. 

I attempted that here: https://gist.github.com/chasemc/210b71386b107fe6daded8f31a395c70, but there's caveats with the implementation, like heavier weighting of higher-mass values. However, provided the same low mass, high mass, and ppm (error), it maps all samples onto the same vector and so this "binning" only has to be performed once on addition of a sample O(1).


> I am curious whether there is a use case in binning large amounts of spectra at once. Do you have any insights on this? In this case, "large" would mean, to start with, what you've identified: 100s to 1000s. Additionally, what about higher ranges: 8,000, 40,000, hundreds of thousands, millions, etc.?

As above, addition of a new sample to the database and/or searching a database. Our lab has been and will be routinely comparing 1000's, and with a growing database this will easily turn into 10's of thousands.
